# Generated by Django 4.1.5 on 2024-07-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0017_alter_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_payment_signature',
            new_name='razorpay_signature',
        ),
    ]
