# Generated by Django 4.1.5 on 2024-07-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0021_customer_groups_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
    ]
