# Generated by Django 4.1.5 on 2024-07-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0023_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Panel_AuthToken',
        ),
    ]
