# Generated by Django 4.1.5 on 2024-07-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0029_remove_cart_product_remove_cart_quantity_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.customer'),
        ),
    ]
